export const currencies = [
    { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
    { code: "ALL", name: "Albanian Lek", symbol: "L" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏" },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
    { code: "BSD", name: "Bahamian Dollar", symbol: "$" },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    { code: "BBD", name: "Barbadian Dollar", symbol: "$" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$" },
    { code: "BMD", name: "Bermudian Dollar", symbol: "$" },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
    { code: "BWP", name: "Botswanan Pula", symbol: "P" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "BND", name: "Brunei Dollar", symbol: "B$" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc" },
    { code: "KYD", name: "Cayman Islands Dollar", symbol: "$" },
    { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA" },
    { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA" },
    { code: "XPF", name: "CFP Franc", symbol: "₣" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "KMF", name: "Comorian Franc", symbol: "CF" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { code: "CUP", name: "Cuban Peso", symbol: "₱" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
    { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "FKP", name: "Falkland Islands Pound", symbol: "£" },
    { code: "FJD", name: "Fijian Dollar", symbol: "$" },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
    { code: "GEL", name: "Georgian Lari", symbol: "₾" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
    { code: "GIP", name: "Gibraltar Pound", symbol: "£" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
    { code: "GNF", name: "Guinean Franc", symbol: "FG" },
    { code: "GYD", name: "Guyanese Dollar", symbol: "$" },
    { code: "HTG", name: "Haitian Gourde", symbol: "G" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { code: "KGS", name: "Kyrgystani Som", symbol: "с" },
    { code: "LAK", name: "Laotian Kip", symbol: "₭" },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
    { code: "LSL", name: "Lesotho Loti", symbol: "L" },
    { code: "LRD", name: "Liberian Dollar", symbol: "$" },
    { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
    { code: "MOP", name: "Macanese Pataca", symbol: "P" },
    { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
    { code: "MRO", name: "Mauritanian Ouguiya", symbol: "UM" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
    { code: "MXN", name: "Mexican Peso", symbol: "Mex$" },
    { code: "MDL", name: "Moldovan Leu", symbol: "L" },
    { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
    { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
    { code: "NAD", name: "Namibian Dollar", symbol: "$" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
    { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "KPW", name: "North Korean Won", symbol: "₩" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
    { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/." },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "QAR", name: "Qatari Rial", symbol: "ر.ق" },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
    { code: "SHP", name: "Saint Helena Pound", symbol: "£" },
    { code: "WST", name: "Samoan Tala", symbol: "T" },
    { code: "STD", name: "São Tomé & Príncipe Dobra", symbol: "Db" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
    { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "$" },
    { code: "SOS", name: "Somali Shilling", symbol: "Sh" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "SSP", name: "South Sudanese Pound", symbol: "£" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
    { code: "SRD", name: "Surinamese Dollar", symbol: "$" },
    { code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
    { code: "SYP", name: "Syrian Pound", symbol: "£" },
    { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
    { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "$" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "TMT", name: "Turkmenistani Manat", symbol: "m" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ" },
    { code: "GBP", name: "United Kingdom Pound", symbol: "£" },
    { code: "USD", name: "United States Dollar", symbol: "$" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
    { code: "UZS", name: "Uzbekistani Som", symbol: "лв" },
    { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt" },
    { code: "VEF", name: "Venezuelan Bolívar", symbol: "Bs" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" }
];
